language: node_js

sudo: false

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

env:
  global:
    - GITHUB_REPO: github.com/liiishenggg/liiishenggg.github.io
    - CODING_REPO: github.com/liiishenggg/liiishenggg.github.io

before_install:
  - export TZ=Asia/Shanghai

script:
  - yarn run build

after_success:
  - git config user.name "liiishenggg"
  - git config user.email "liiishenggg@163.com"
  - git clone https://${CODING_REPO} ./old-docs
  - cp -r ./old-docs/.git ./docs 
  - cd ./docs
  - git add -A
  - git commit -m "deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git branch -a
  - git push --force --quiet "https://liiishenggg:{CI_TOKEN}@${GITHUB_REPO}" gh-pages:gh-pages
